baseURL = 'https://rohernandezz.github.io/DIMELA.mx'
languageCode = 'en-us'
title = 'DIMELA: Directorio Mexicano de Letristas'

enableEmoji = true
removePathAccents = true

[taxonomies]
  servicio = "servicios"
  estado   = "estado"