-- Sample curated tags for local D1 (profiles + publications).
-- Applied by db:sync:local after migration 009. Safe to re-run.
-- Source: public/data/profiles.json / mockProfiles seed.

UPDATE profiles SET tags = '["Tipografía custom","Tipo para marca","Packaging","Talleres"]' WHERE slug = 'romina-hernandez';
UPDATE profile_publications SET tags = '["Tipografía custom","Tipo para marca","Packaging","Talleres"]' WHERE slug = 'romina-hernandez';
UPDATE profiles SET tags = '["Tipografía custom","Editorial","Tipo para marca"]' WHERE slug = 'cristobal-henestrosa';
UPDATE profile_publications SET tags = '["Tipografía custom","Editorial","Tipo para marca"]' WHERE slug = 'cristobal-henestrosa';
UPDATE profiles SET tags = '["Murales","Packaging","Brush","Logotipo"]' WHERE slug = 'miguel-contreras';
UPDATE profile_publications SET tags = '["Murales","Packaging","Brush","Logotipo"]' WHERE slug = 'miguel-contreras';
UPDATE profiles SET tags = '["Grabado caligráfico","Editorial"]' WHERE slug = 'cecilia-del-castillo';
UPDATE profile_publications SET tags = '["Grabado caligráfico","Editorial"]' WHERE slug = 'cecilia-del-castillo';
UPDATE profiles SET tags = '["Editorial","Packaging"]' WHERE slug = 'antonio-mejia-lechuga';
UPDATE profile_publications SET tags = '["Editorial","Packaging"]' WHERE slug = 'antonio-mejia-lechuga';
UPDATE profiles SET tags = '["Murales","Gran formato","Fachada","Señalética"]' WHERE slug = 'giovanni-bautista';
UPDATE profile_publications SET tags = '["Murales","Gran formato","Fachada","Señalética"]' WHERE slug = 'giovanni-bautista';
UPDATE profiles SET tags = '["Tipo para marca","Activaciones","Neon","Logotipo"]' WHERE slug = 'mara-osman';
UPDATE profile_publications SET tags = '["Tipo para marca","Activaciones","Neon","Logotipo"]' WHERE slug = 'mara-osman';
UPDATE profiles SET tags = '["Pizarras","Fachada","Señalética","Retail"]' WHERE slug = 'sandra-morales';
UPDATE profile_publications SET tags = '["Pizarras","Fachada","Señalética","Retail"]' WHERE slug = 'sandra-morales';
UPDATE profiles SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'ana-reyes-aguascalientes-base';
UPDATE profile_publications SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'ana-reyes-aguascalientes-base';
UPDATE profiles SET tags = '["Tipo para marca"]' WHERE slug = 'bruno-garcia-baja-california-base';
UPDATE profile_publications SET tags = '["Tipo para marca"]' WHERE slug = 'bruno-garcia-baja-california-base';
UPDATE profiles SET tags = '["Murales"]' WHERE slug = 'camila-torres-baja-california-sur-base';
UPDATE profile_publications SET tags = '["Murales"]' WHERE slug = 'camila-torres-baja-california-sur-base';
UPDATE profiles SET tags = '["Gran formato"]' WHERE slug = 'diego-castillo-campeche-base';
UPDATE profile_publications SET tags = '["Gran formato"]' WHERE slug = 'diego-castillo-campeche-base';
UPDATE profiles SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'elena-ruiz-chiapas-base';
UPDATE profile_publications SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'elena-ruiz-chiapas-base';
UPDATE profiles SET tags = '["Activaciones","Talleres","Editorial"]' WHERE slug = 'fernanda-reyes-chihuahua-base';
UPDATE profile_publications SET tags = '["Activaciones","Talleres","Editorial"]' WHERE slug = 'fernanda-reyes-chihuahua-base';
UPDATE profiles SET tags = '["Pizarras"]' WHERE slug = 'gabriel-garcia-ciudad-de-mexico-base';
UPDATE profile_publications SET tags = '["Pizarras"]' WHERE slug = 'gabriel-garcia-ciudad-de-mexico-base';
UPDATE profiles SET tags = '["Brush"]' WHERE slug = 'helena-torres-coahuila-base';
UPDATE profile_publications SET tags = '["Brush"]' WHERE slug = 'helena-torres-coahuila-base';
UPDATE profiles SET tags = '["Neon","Retail"]' WHERE slug = 'ivan-castillo-colima-base';
UPDATE profile_publications SET tags = '["Neon","Retail"]' WHERE slug = 'ivan-castillo-colima-base';
UPDATE profiles SET tags = '["Packaging"]' WHERE slug = 'jimena-ruiz-durango-base';
UPDATE profile_publications SET tags = '["Packaging"]' WHERE slug = 'jimena-ruiz-durango-base';
UPDATE profiles SET tags = '["Talleres","Logotipo","Gran formato"]' WHERE slug = 'kevin-reyes-guanajuato-base';
UPDATE profile_publications SET tags = '["Talleres","Logotipo","Gran formato"]' WHERE slug = 'kevin-reyes-guanajuato-base';
UPDATE profiles SET tags = '["Señalética"]' WHERE slug = 'lucia-garcia-guerrero-base';
UPDATE profile_publications SET tags = '["Señalética"]' WHERE slug = 'lucia-garcia-guerrero-base';
UPDATE profiles SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'marco-torres-hidalgo-base';
UPDATE profile_publications SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'marco-torres-hidalgo-base';
UPDATE profiles SET tags = '["Retail"]' WHERE slug = 'natalia-castillo-jalisco-base';
UPDATE profile_publications SET tags = '["Retail"]' WHERE slug = 'natalia-castillo-jalisco-base';
UPDATE profiles SET tags = '["Editorial"]' WHERE slug = 'oscar-ruiz-estado-de-mexico-base';
UPDATE profile_publications SET tags = '["Editorial"]' WHERE slug = 'oscar-ruiz-estado-de-mexico-base';
UPDATE profiles SET tags = '["Logotipo","Grabado caligráfico","Neon"]' WHERE slug = 'paula-reyes-michoacan-base';
UPDATE profile_publications SET tags = '["Logotipo","Grabado caligráfico","Neon"]' WHERE slug = 'paula-reyes-michoacan-base';
UPDATE profiles SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'rafael-garcia-morelos-base';
UPDATE profile_publications SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'rafael-garcia-morelos-base';
UPDATE profiles SET tags = '["Tipo para marca"]' WHERE slug = 'sofia-torres-nayarit-base';
UPDATE profile_publications SET tags = '["Tipo para marca"]' WHERE slug = 'sofia-torres-nayarit-base';
UPDATE profiles SET tags = '["Murales"]' WHERE slug = 'tomas-castillo-nuevo-leon-base';
UPDATE profile_publications SET tags = '["Murales"]' WHERE slug = 'tomas-castillo-nuevo-leon-base';
UPDATE profiles SET tags = '["Gran formato"]' WHERE slug = 'valeria-ruiz-oaxaca-base';
UPDATE profile_publications SET tags = '["Gran formato"]' WHERE slug = 'valeria-ruiz-oaxaca-base';
UPDATE profiles SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'ximena-reyes-puebla-base';
UPDATE profile_publications SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'ximena-reyes-puebla-base';
UPDATE profiles SET tags = '["Activaciones"]' WHERE slug = 'yuri-garcia-queretaro-base';
UPDATE profile_publications SET tags = '["Activaciones"]' WHERE slug = 'yuri-garcia-queretaro-base';
UPDATE profiles SET tags = '["Pizarras"]' WHERE slug = 'ana-torres-quintana-roo-base';
UPDATE profile_publications SET tags = '["Pizarras"]' WHERE slug = 'ana-torres-quintana-roo-base';
UPDATE profiles SET tags = '["Brush"]' WHERE slug = 'bruno-castillo-san-luis-potosi-base';
UPDATE profile_publications SET tags = '["Brush"]' WHERE slug = 'bruno-castillo-san-luis-potosi-base';
UPDATE profiles SET tags = '["Neon","Retail"]' WHERE slug = 'camila-ruiz-sinaloa-base';
UPDATE profile_publications SET tags = '["Neon","Retail"]' WHERE slug = 'camila-ruiz-sinaloa-base';
UPDATE profiles SET tags = '["Packaging","Editorial","Murales"]' WHERE slug = 'diego-reyes-sonora-base';
UPDATE profile_publications SET tags = '["Packaging","Editorial","Murales"]' WHERE slug = 'diego-reyes-sonora-base';
UPDATE profiles SET tags = '["Talleres"]' WHERE slug = 'elena-garcia-tabasco-base';
UPDATE profile_publications SET tags = '["Talleres"]' WHERE slug = 'elena-garcia-tabasco-base';
UPDATE profiles SET tags = '["Señalética"]' WHERE slug = 'fernanda-torres-tamaulipas-base';
UPDATE profile_publications SET tags = '["Señalética"]' WHERE slug = 'fernanda-torres-tamaulipas-base';
UPDATE profiles SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'gabriel-castillo-tlaxcala-base';
UPDATE profile_publications SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'gabriel-castillo-tlaxcala-base';
UPDATE profiles SET tags = '["Retail"]' WHERE slug = 'helena-ruiz-veracruz-base';
UPDATE profile_publications SET tags = '["Retail"]' WHERE slug = 'helena-ruiz-veracruz-base';
UPDATE profiles SET tags = '["Editorial","Gran formato","Brush"]' WHERE slug = 'ivan-reyes-yucatan-base';
UPDATE profile_publications SET tags = '["Editorial","Gran formato","Brush"]' WHERE slug = 'ivan-reyes-yucatan-base';
UPDATE profiles SET tags = '["Logotipo"]' WHERE slug = 'jimena-garcia-zacatecas-base';
UPDATE profile_publications SET tags = '["Logotipo"]' WHERE slug = 'jimena-garcia-zacatecas-base';
UPDATE profiles SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'kevin-torres-fuera-de-mexico-base';
UPDATE profile_publications SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'kevin-torres-fuera-de-mexico-base';
UPDATE profiles SET tags = '["Tipo para marca"]' WHERE slug = 'lucia-castillo-ciudad-de-mexico-hub0';
UPDATE profile_publications SET tags = '["Tipo para marca"]' WHERE slug = 'lucia-castillo-ciudad-de-mexico-hub0';
UPDATE profiles SET tags = '["Murales"]' WHERE slug = 'marco-ruiz-ciudad-de-mexico-hub1';
UPDATE profile_publications SET tags = '["Murales"]' WHERE slug = 'marco-ruiz-ciudad-de-mexico-hub1';
UPDATE profiles SET tags = '["Gran formato","Neon","Fachada"]' WHERE slug = 'natalia-reyes-ciudad-de-mexico-hub2';
UPDATE profile_publications SET tags = '["Gran formato","Neon","Fachada"]' WHERE slug = 'natalia-reyes-ciudad-de-mexico-hub2';
UPDATE profiles SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'oscar-garcia-ciudad-de-mexico-hub3';
UPDATE profile_publications SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'oscar-garcia-ciudad-de-mexico-hub3';
UPDATE profiles SET tags = '["Activaciones"]' WHERE slug = 'paula-torres-ciudad-de-mexico-hub4';
UPDATE profile_publications SET tags = '["Activaciones"]' WHERE slug = 'paula-torres-ciudad-de-mexico-hub4';
UPDATE profiles SET tags = '["Pizarras"]' WHERE slug = 'rafael-castillo-ciudad-de-mexico-hub5';
UPDATE profile_publications SET tags = '["Pizarras"]' WHERE slug = 'rafael-castillo-ciudad-de-mexico-hub5';
UPDATE profiles SET tags = '["Brush"]' WHERE slug = 'sofia-ruiz-ciudad-de-mexico-hub6';
UPDATE profile_publications SET tags = '["Brush"]' WHERE slug = 'sofia-ruiz-ciudad-de-mexico-hub6';
UPDATE profiles SET tags = '["Neon","Retail"]' WHERE slug = 'tomas-reyes-ciudad-de-mexico-hub7';
UPDATE profile_publications SET tags = '["Neon","Retail"]' WHERE slug = 'tomas-reyes-ciudad-de-mexico-hub7';
UPDATE profiles SET tags = '["Packaging"]' WHERE slug = 'valeria-garcia-puebla-hub0';
UPDATE profile_publications SET tags = '["Packaging"]' WHERE slug = 'valeria-garcia-puebla-hub0';
UPDATE profiles SET tags = '["Talleres"]' WHERE slug = 'ximena-torres-puebla-hub1';
UPDATE profile_publications SET tags = '["Talleres"]' WHERE slug = 'ximena-torres-puebla-hub1';
UPDATE profiles SET tags = '["Señalética"]' WHERE slug = 'yuri-castillo-puebla-hub2';
UPDATE profile_publications SET tags = '["Señalética"]' WHERE slug = 'yuri-castillo-puebla-hub2';
UPDATE profiles SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'ana-ruiz-puebla-hub3';
UPDATE profile_publications SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'ana-ruiz-puebla-hub3';
UPDATE profiles SET tags = '["Retail","Murales","Pizarras"]' WHERE slug = 'bruno-reyes-puebla-hub4';
UPDATE profile_publications SET tags = '["Retail","Murales","Pizarras"]' WHERE slug = 'bruno-reyes-puebla-hub4';
UPDATE profiles SET tags = '["Editorial"]' WHERE slug = 'camila-garcia-jalisco-hub0';
UPDATE profile_publications SET tags = '["Editorial"]' WHERE slug = 'camila-garcia-jalisco-hub0';
UPDATE profiles SET tags = '["Logotipo"]' WHERE slug = 'diego-torres-jalisco-hub1';
UPDATE profile_publications SET tags = '["Logotipo"]' WHERE slug = 'diego-torres-jalisco-hub1';
UPDATE profiles SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'elena-castillo-jalisco-hub2';
UPDATE profile_publications SET tags = '["Tipografía custom","Activaciones"]' WHERE slug = 'elena-castillo-jalisco-hub2';
UPDATE profiles SET tags = '["Tipo para marca"]' WHERE slug = 'fernanda-ruiz-jalisco-hub3';
UPDATE profile_publications SET tags = '["Tipo para marca"]' WHERE slug = 'fernanda-ruiz-jalisco-hub3';
UPDATE profiles SET tags = '["Murales","Brush","Señalética"]' WHERE slug = 'gabriel-reyes-nuevo-leon-hub0';
UPDATE profile_publications SET tags = '["Murales","Brush","Señalética"]' WHERE slug = 'gabriel-reyes-nuevo-leon-hub0';
UPDATE profiles SET tags = '["Gran formato"]' WHERE slug = 'helena-garcia-nuevo-leon-hub1';
UPDATE profile_publications SET tags = '["Gran formato"]' WHERE slug = 'helena-garcia-nuevo-leon-hub1';
UPDATE profiles SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'ivan-torres-nuevo-leon-hub2';
UPDATE profile_publications SET tags = '["Grabado caligráfico","Packaging"]' WHERE slug = 'ivan-torres-nuevo-leon-hub2';
UPDATE profiles SET tags = '["Activaciones"]' WHERE slug = 'jimena-castillo-oaxaca-hub0';
UPDATE profile_publications SET tags = '["Activaciones"]' WHERE slug = 'jimena-castillo-oaxaca-hub0';
UPDATE profiles SET tags = '["Pizarras"]' WHERE slug = 'kevin-ruiz-oaxaca-hub1';
UPDATE profile_publications SET tags = '["Pizarras"]' WHERE slug = 'kevin-ruiz-oaxaca-hub1';
UPDATE profiles SET tags = '["Brush","Fachada","Tipografía custom"]' WHERE slug = 'lucia-reyes-oaxaca-hub2';
UPDATE profile_publications SET tags = '["Brush","Fachada","Tipografía custom"]' WHERE slug = 'lucia-reyes-oaxaca-hub2';
UPDATE profiles SET tags = '["Neon","Retail"]' WHERE slug = 'marco-garcia-queretaro-hub0';
UPDATE profile_publications SET tags = '["Neon","Retail"]' WHERE slug = 'marco-garcia-queretaro-hub0';
UPDATE profiles SET tags = '["Packaging"]' WHERE slug = 'natalia-torres-queretaro-hub1';
UPDATE profile_publications SET tags = '["Packaging"]' WHERE slug = 'natalia-torres-queretaro-hub1';
UPDATE profiles SET tags = '["Talleres"]' WHERE slug = 'oscar-castillo-yucatan-hub0';
UPDATE profile_publications SET tags = '["Talleres"]' WHERE slug = 'oscar-castillo-yucatan-hub0';
UPDATE profiles SET tags = '["Señalética"]' WHERE slug = 'paula-ruiz-yucatan-hub1';
UPDATE profile_publications SET tags = '["Señalética"]' WHERE slug = 'paula-ruiz-yucatan-hub1';
UPDATE profiles SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'rafael-reyes-veracruz-hub0';
UPDATE profile_publications SET tags = '["Fachada","Tipo para marca"]' WHERE slug = 'rafael-reyes-veracruz-hub0';
UPDATE profiles SET tags = '["Retail"]' WHERE slug = 'sofia-garcia-veracruz-hub1';
UPDATE profile_publications SET tags = '["Retail"]' WHERE slug = 'sofia-garcia-veracruz-hub1';
