-- Auto-generated from src/data/mockProfiles.ts — do not edit by hand
DELETE FROM profile_publications;
DELETE FROM profiles;

INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('romina-hernandez', 'Romina Hernández', 'Ciudad de México', '["Diseño de Tipografía","Lettering","Ingeniería de Fuentes"]', '["Tipografía custom","Tipo para marca","Packaging","Talleres"]', '<p>Desde México, hago letras con amor y buen sazón. Tipografía a la medida, lettering e ingeniería en Tortilla.studio.</p><h2>Tipografía con raíz</h2><p>Trabajo con estudios, marcas y editoriales que buscan una voz tipográfica clara y con raíz mexicana — desde logotipos hasta familias completas para texto corrido, UI y packaging.</p><p>Me importa el oficio: boceto, revisión, kerning, pruebas en contexto real. Cada proyecto empieza con escucha y termina con archivos listos para producción.</p><h2>Colaboración</h2><p>Talleres, charlas y colaboraciones con el Colegio de Diseñadores, TMX y equipos creativos en CDMX y remoto. Si tienes un proyecto — editorial, marca o fuente propia — escríbeme.</p>', 'https://tortilla.studio', 'pro', 0, '/mock/cover-warm.svg', NULL, '.profile-card .bio-lead,
.profile-detail .profile-bio > p:first-child {
  font-family: ''Pigeonette'', sans-serif;
  font-size: 1.35rem;
  line-height: 1.35;
}
.profile-detail .profile-bio {
  font-family: ''Pigeonette'', sans-serif;
  font-size: 1.125rem;
  line-height: 1.6;
}
.profile-detail .profile-bio h2 {
  font-family: ''Pigeonette'', sans-serif;
  font-size: 1.5rem;
}
.profile-detail h1 {
  font-family: ''Pigeonette'', sans-serif;
  letter-spacing: 0.02em;
}', '[{"id":"pigeonette","family":"Pigeonette","url":"/media/profiles/user_romina/font/pigeonette.woff2","format":"woff2"}]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('cristobal-henestrosa', 'Cristóbal Henestrosa', 'Ciudad de México', '["Diseño de Tipografía","Diseño Editorial"]', '["Tipografía custom","Editorial","Tipo para marca"]', '<p>Diseñador tipográfico y editorial. Fuentes para prensa, libros e identidad cultural mexicana.</p><h2>Editorial y prensa</h2><p>He diseñado tipos para periódicos, museos y sellos independientes. Me interesa la legibilidad, el detalle y la historia detrás de cada letra — cómo una familia tipográfica sostiene un tono editorial durante años.</p><p>Desde revistas culturales hasta catálogos de museo, busco sistemas que funcionen en titulares y en notas al pie con la misma voz.</p>', 'https://henestrosatype.com', 'pro', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('miguel-contreras', 'Miguel Contreras', 'Puebla', '["Lettering","Branding","Diseño de Tipografía","Caligrafía"]', '["Murales","Packaging","Brush","Logotipo"]', '<p>Lettering, caligrafía y tipografía para marcas. Proyectos de identidad con trazo propio.</p><h2>Marcas con carácter</h2><p>Desde Puebla trabajo con restaurantes, cervecerías y proyectos culturales que necesitan letras con carácter — mural, empaque o sistema completo.</p><p>El proceso mezcla boceto a mano, refinamiento digital y entrega lista para impresión o pantalla. Me gusta cuando la tipografía se siente hecha para ese negocio, no sacada de un catálogo.</p><p>Disponible para colaboraciones en México y remoto.</p>', 'https://miglconts.com', 'pro', 0, '/mock/cover-green.svg', '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('cecilia-del-castillo', 'Cecilia del Castillo', 'Fuera de México', '["Diseño de Tipografía","Caligrafía"]', '["Grabado caligráfico","Editorial"]', '<p>Mexican type designer &amp; calligrapher. Fuentes y caligrafía para editorial e identidad.</p><h2>Caligrafía y fuentes</h2><p>Vivo entre proyectos editoriales y encargos de caligrafía para invitaciones, libros de artista y piezas de colección.</p><p>Investigo la relación entre trazo manual y sistemas tipográficos digitales — a veces la caligrafía guía una familia completa; otras, la fuente nace directo del lápiz.</p>', 'https://www.instagram.com/ceci_dcd', 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('antonio-mejia-lechuga', 'Antonio Mejía Lechuga', 'Querétaro', '["Diseño Editorial"]', '["Editorial","Packaging"]', '<p>Diseño editorial y tipografía aplicada a libros, revistas y publicaciones independientes.</p><p>En Cuatro Ojos armamos publicaciones con ritmo, jerarquía y cuidado en cada página. Nos gusta el papel, la encuadernación y el detalle que se nota al hojear.</p>', 'https://cuatroojos.com.mx', 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('giovanni-bautista', 'Giovanni Bautista', 'Oaxaca', '["Rotulación Manual","Lettering"]', '["Murales","Gran formato","Fachada","Señalética"]', '<p>Rotulación a mano y lettering para comercio local, fachadas y espacios públicos en Oaxaca.</p><p>Pintura, pincel y color para negocios de barrio, mercados y festivales. Cada letrero cuenta la historia del lugar.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('mara-osman', 'Mara Osman', 'Ciudad de México', '["Branding","Diseño de Tipografía","Lettering","Caligrafía"]', '["Tipo para marca","Activaciones","Neon","Logotipo"]', '<p>Identidad tipográfica, lettering y caligrafía para marcas culturales y editoriales.</p><h2>Sistema y voz</h2><p>Combino investigación, boceto y sistema para que la voz de una marca se sienta coherente en impreso y pantalla.</p><p>Proyectos recientes: festivales, sellos discográficos y identidad para espacios culturales en CDMX.</p><p>Trabajo en paquetes que incluyen logotipo, lettering, selección tipográfica y guías de uso para equipos internos.</p>', NULL, 'pro', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('sandra-morales', 'Sandra Morales', 'Puebla', '["Rotulación Manual"]', '["Pizarras","Fachada","Señalética","Retail"]', '<p>Rotulación manual para negocios, letreros y piezas de señalética con carácter local.</p><p>Trabajo con comercios de Puebla que quieren verse auténticos — sin plantillas, con letra hecha a mano.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ana-reyes-aguascalientes-base', 'Ana Reyes', 'Aguascalientes', '["Lettering","Diseño de Tipografía"]', '["Tipografía custom","Activaciones"]', '<p>Lettering para marca, empaques y piezas editoriales. Basada en Aguascalientes.</p><p>Colaboro con estudios de diseño y marcas que buscan letras con personalidad.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('bruno-garcia-baja-california-base', 'Bruno García', 'Baja California', '["Branding"]', '["Tipo para marca"]', '<p>Branding con foco en tipografía y voz visual. Basada en Baja California.</p><p>Sistemas tipográficos para identidad en todos los puntos de contacto.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('camila-torres-baja-california-sur-base', 'Camila Torres', 'Baja California Sur', '["Diseño de Tipografía"]', '["Murales"]', '<p>Diseño de fuentes para editorial, marca y pantalla. Basada en Baja California Sur.</p><p>Familias a medida y ajustes finos para editorial y UI.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('diego-castillo-campeche-base', 'Diego Castillo', 'Campeche', '["Diseño Editorial","Ingeniería de Fuentes"]', '["Gran formato"]', '<p>Libros, revistas y piezas impresas con cuidado tipográfico. Basada en Campeche.</p><p>Libros, revistas y catálogos con cuidado en cada página.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('elena-ruiz-chiapas-base', 'Elena Ruiz', 'Chiapas', '["Caligrafía"]', '["Grabado caligráfico","Packaging"]', '<p>Caligrafía contemporánea para marca y piezas únicas. Basada en Chiapas.</p><p>Piezas únicas para invitaciones, logotipos y proyectos especiales.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('fernanda-reyes-chihuahua-base', 'Fernanda Reyes', 'Chihuahua', '["Ingeniería de Fuentes"]', '["Activaciones","Talleres","Editorial"]', '<p>Soporte técnico para diseñadores de fuentes. Basada en Chihuahua.</p><p>Soporte técnico para lanzar fuentes sin sorpresas.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('gabriel-garcia-ciudad-de-mexico-base', 'Gabriel García', 'Ciudad de México', '["Rotulación Manual","Branding"]', '["Pizarras"]', '<p>Rotulación a mano para fachadas y comercio local. Basada en Ciudad de México.</p><p>Color, proporción y legibilidad para fachadas y señalética.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('helena-torres-coahuila-base', 'Helena Torres', 'Coahuila', '["Lettering"]', '["Brush"]', '<p>Letras dibujadas a mano para identidad y campaña. Basada en Coahuila.</p><p>Boceto, refinamiento y entrega para impreso y pantalla.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ivan-castillo-colima-base', 'Iván Castillo', 'Colima', '["Branding"]', '["Neon","Retail"]', '<p>Identidad tipográfica y sistemas de marca. Basada en Colima.</p><p>Investigo la voz de cada marca antes de dibujar la primera letra.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('jimena-ruiz-durango-base', 'Jimena Ruiz', 'Durango', '["Diseño de Tipografía","Caligrafía"]', '["Packaging"]', '<p>Familias tipográficas a la medida y retail. Basada en Durango.</p><p>Desde el concepto hasta los archivos listos para producción.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('kevin-reyes-guanajuato-base', 'Kevin Reyes', 'Guanajuato', '["Diseño Editorial"]', '["Talleres","Logotipo","Gran formato"]', '<p>Diseño editorial y tipografía aplicada a publicaciones. Basada en Guanajuato.</p><p>Maquetación, elección tipográfica y ritmo de lectura.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('lucia-garcia-guerrero-base', 'Lucia García', 'Guerrero', '["Caligrafía"]', '["Señalética"]', '<p>Trazo caligráfico para invitaciones, logos y arte. Basada en Guerrero.</p><p>Tinta, pincel y digital para encargos editoriales y de marca.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('marco-torres-hidalgo-base', 'Marco Torres', 'Hidalgo', '["Ingeniería de Fuentes","Lettering"]', '["Fachada","Tipo para marca"]', '<p>Ingeniería tipográfica: producción, kerning y exportación. Basada en Hidalgo.</p><p>Kerning, hinting y exportación para equipos de diseño.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('natalia-castillo-jalisco-base', 'Natalia Castillo', 'Jalisco', '["Rotulación Manual"]', '["Retail"]', '<p>Letreros y señalética con trazo manual. Basada en Jalisco.</p><p>Letreros pintados a mano para comercio y espacios públicos.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('oscar-ruiz-estado-de-mexico-base', 'Oscar Ruiz', 'Estado de México', '["Lettering"]', '["Editorial"]', '<p>Lettering para marca, empaques y piezas editoriales. Basada en Estado de México.</p><p>Colaboro con estudios de diseño y marcas que buscan letras con personalidad.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('paula-reyes-michoacan-base', 'Paula Reyes', 'Michoacán', '["Branding","Diseño Editorial"]', '["Logotipo","Grabado caligráfico","Neon"]', '<p>Branding con foco en tipografía y voz visual. Basada en Michoacán.</p><p>Sistemas tipográficos para identidad en todos los puntos de contacto.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('rafael-garcia-morelos-base', 'Rafael García', 'Morelos', '["Diseño de Tipografía"]', '["Tipografía custom","Activaciones"]', '<p>Diseño de fuentes para editorial, marca y pantalla. Basada en Morelos.</p><p>Familias a medida y ajustes finos para editorial y UI.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('sofia-torres-nayarit-base', 'Sofía Torres', 'Nayarit', '["Diseño Editorial"]', '["Tipo para marca"]', '<p>Libros, revistas y piezas impresas con cuidado tipográfico. Basada en Nayarit.</p><p>Libros, revistas y catálogos con cuidado en cada página.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('tomas-castillo-nuevo-leon-base', 'Tomás Castillo', 'Nuevo León', '["Caligrafía","Rotulación Manual"]', '["Murales"]', '<p>Caligrafía contemporánea para marca y piezas únicas. Basada en Nuevo León.</p><p>Piezas únicas para invitaciones, logotipos y proyectos especiales.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('valeria-ruiz-oaxaca-base', 'Valeria Ruiz', 'Oaxaca', '["Ingeniería de Fuentes"]', '["Gran formato"]', '<p>Soporte técnico para diseñadores de fuentes. Basada en Oaxaca.</p><p>Soporte técnico para lanzar fuentes sin sorpresas.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ximena-reyes-puebla-base', 'Ximena Reyes', 'Puebla', '["Rotulación Manual"]', '["Grabado caligráfico","Packaging"]', '<p>Rotulación a mano para fachadas y comercio local. Basada en Puebla.</p><p>Color, proporción y legibilidad para fachadas y señalética.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('yuri-garcia-queretaro-base', 'Yuri García', 'Querétaro', '["Lettering","Diseño de Tipografía"]', '["Activaciones"]', '<p>Letras dibujadas a mano para identidad y campaña. Basada en Querétaro.</p><p>Boceto, refinamiento y entrega para impreso y pantalla.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ana-torres-quintana-roo-base', 'Ana Torres', 'Quintana Roo', '["Branding"]', '["Pizarras"]', '<p>Identidad tipográfica y sistemas de marca. Basada en Quintana Roo.</p><p>Investigo la voz de cada marca antes de dibujar la primera letra.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('bruno-castillo-san-luis-potosi-base', 'Bruno Castillo', 'San Luis Potosí', '["Diseño de Tipografía"]', '["Brush"]', '<p>Familias tipográficas a la medida y retail. Basada en San Luis Potosí.</p><p>Desde el concepto hasta los archivos listos para producción.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('camila-ruiz-sinaloa-base', 'Camila Ruiz', 'Sinaloa', '["Diseño Editorial","Ingeniería de Fuentes"]', '["Neon","Retail"]', '<p>Diseño editorial y tipografía aplicada a publicaciones. Basada en Sinaloa.</p><p>Maquetación, elección tipográfica y ritmo de lectura.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('diego-reyes-sonora-base', 'Diego Reyes', 'Sonora', '["Caligrafía"]', '["Packaging","Editorial","Murales"]', '<p>Trazo caligráfico para invitaciones, logos y arte. Basada en Sonora.</p><p>Tinta, pincel y digital para encargos editoriales y de marca.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('elena-garcia-tabasco-base', 'Elena García', 'Tabasco', '["Ingeniería de Fuentes"]', '["Talleres"]', '<p>Ingeniería tipográfica: producción, kerning y exportación. Basada en Tabasco.</p><p>Kerning, hinting y exportación para equipos de diseño.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('fernanda-torres-tamaulipas-base', 'Fernanda Torres', 'Tamaulipas', '["Rotulación Manual","Branding"]', '["Señalética"]', '<p>Letreros y señalética con trazo manual. Basada en Tamaulipas.</p><p>Letreros pintados a mano para comercio y espacios públicos.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('gabriel-castillo-tlaxcala-base', 'Gabriel Castillo', 'Tlaxcala', '["Lettering"]', '["Fachada","Tipo para marca"]', '<p>Lettering para marca, empaques y piezas editoriales. Basada en Tlaxcala.</p><p>Colaboro con estudios de diseño y marcas que buscan letras con personalidad.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('helena-ruiz-veracruz-base', 'Helena Ruiz', 'Veracruz', '["Branding"]', '["Retail"]', '<p>Branding con foco en tipografía y voz visual. Basada en Veracruz.</p><p>Sistemas tipográficos para identidad en todos los puntos de contacto.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ivan-reyes-yucatan-base', 'Iván Reyes', 'Yucatán', '["Diseño de Tipografía","Caligrafía"]', '["Editorial","Gran formato","Brush"]', '<p>Diseño de fuentes para editorial, marca y pantalla. Basada en Yucatán.</p><p>Familias a medida y ajustes finos para editorial y UI.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('jimena-garcia-zacatecas-base', 'Jimena García', 'Zacatecas', '["Diseño Editorial"]', '["Logotipo"]', '<p>Libros, revistas y piezas impresas con cuidado tipográfico. Basada en Zacatecas.</p><p>Libros, revistas y catálogos con cuidado en cada página.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('kevin-torres-fuera-de-mexico-base', 'Kevin Torres', 'Fuera de México', '["Caligrafía"]', '["Tipografía custom","Activaciones"]', '<p>Caligrafía contemporánea para marca y piezas únicas. Basada en Fuera de México.</p><p>Piezas únicas para invitaciones, logotipos y proyectos especiales.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('lucia-castillo-ciudad-de-mexico-hub0', 'Lucia Castillo', 'Ciudad de México', '["Ingeniería de Fuentes","Lettering"]', '["Tipo para marca"]', '<p>Soporte técnico para diseñadores de fuentes. Basada en Ciudad de México.</p><p>Soporte técnico para lanzar fuentes sin sorpresas.</p>', NULL, 'free', 0, '/mock/mara-featured.png', '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('marco-ruiz-ciudad-de-mexico-hub1', 'Marco Ruiz', 'Ciudad de México', '["Rotulación Manual"]', '["Murales"]', '<p>Rotulación a mano para fachadas y comercio local. Basada en Ciudad de México.</p><p>Color, proporción y legibilidad para fachadas y señalética.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('natalia-reyes-ciudad-de-mexico-hub2', 'Natalia Reyes', 'Ciudad de México', '["Lettering"]', '["Gran formato","Neon","Fachada"]', '<p>Letras dibujadas a mano para identidad y campaña. Basada en Ciudad de México.</p><p>Boceto, refinamiento y entrega para impreso y pantalla.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('oscar-garcia-ciudad-de-mexico-hub3', 'Oscar García', 'Ciudad de México', '["Branding","Diseño Editorial"]', '["Grabado caligráfico","Packaging"]', '<p>Identidad tipográfica y sistemas de marca. Basada en Ciudad de México.</p><p>Investigo la voz de cada marca antes de dibujar la primera letra.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('paula-torres-ciudad-de-mexico-hub4', 'Paula Torres', 'Ciudad de México', '["Diseño de Tipografía"]', '["Activaciones"]', '<p>Familias tipográficas a la medida y retail. Basada en Ciudad de México.</p><p>Desde el concepto hasta los archivos listos para producción.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('rafael-castillo-ciudad-de-mexico-hub5', 'Rafael Castillo', 'Ciudad de México', '["Diseño Editorial"]', '["Pizarras"]', '<p>Diseño editorial y tipografía aplicada a publicaciones. Basada en Ciudad de México.</p><p>Maquetación, elección tipográfica y ritmo de lectura.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('sofia-ruiz-ciudad-de-mexico-hub6', 'Sofía Ruiz', 'Ciudad de México', '["Caligrafía","Rotulación Manual"]', '["Brush"]', '<p>Trazo caligráfico para invitaciones, logos y arte. Basada en Ciudad de México.</p><p>Tinta, pincel y digital para encargos editoriales y de marca.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('tomas-reyes-ciudad-de-mexico-hub7', 'Tomás Reyes', 'Ciudad de México', '["Ingeniería de Fuentes"]', '["Neon","Retail"]', '<p>Ingeniería tipográfica: producción, kerning y exportación. Basada en Ciudad de México.</p><p>Kerning, hinting y exportación para equipos de diseño.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('valeria-garcia-puebla-hub0', 'Valeria García', 'Puebla', '["Rotulación Manual"]', '["Packaging"]', '<p>Letreros y señalética con trazo manual. Basada en Puebla.</p><p>Letreros pintados a mano para comercio y espacios públicos.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ximena-torres-puebla-hub1', 'Ximena Torres', 'Puebla', '["Lettering","Diseño de Tipografía"]', '["Talleres"]', '<p>Lettering para marca, empaques y piezas editoriales. Basada en Puebla.</p><p>Colaboro con estudios de diseño y marcas que buscan letras con personalidad.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('yuri-castillo-puebla-hub2', 'Yuri Castillo', 'Puebla', '["Branding"]', '["Señalética"]', '<p>Branding con foco en tipografía y voz visual. Basada en Puebla.</p><p>Sistemas tipográficos para identidad en todos los puntos de contacto.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ana-ruiz-puebla-hub3', 'Ana Ruiz', 'Puebla', '["Diseño de Tipografía"]', '["Fachada","Tipo para marca"]', '<p>Diseño de fuentes para editorial, marca y pantalla. Basada en Puebla.</p><p>Familias a medida y ajustes finos para editorial y UI.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('bruno-reyes-puebla-hub4', 'Bruno Reyes', 'Puebla', '["Diseño Editorial","Ingeniería de Fuentes"]', '["Retail","Murales","Pizarras"]', '<p>Libros, revistas y piezas impresas con cuidado tipográfico. Basada en Puebla.</p><p>Libros, revistas y catálogos con cuidado en cada página.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('camila-garcia-jalisco-hub0', 'Camila García', 'Jalisco', '["Caligrafía"]', '["Editorial"]', '<p>Caligrafía contemporánea para marca y piezas únicas. Basada en Jalisco.</p><p>Piezas únicas para invitaciones, logotipos y proyectos especiales.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('diego-torres-jalisco-hub1', 'Diego Torres', 'Jalisco', '["Ingeniería de Fuentes"]', '["Logotipo"]', '<p>Soporte técnico para diseñadores de fuentes. Basada en Jalisco.</p><p>Soporte técnico para lanzar fuentes sin sorpresas.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('elena-castillo-jalisco-hub2', 'Elena Castillo', 'Jalisco', '["Rotulación Manual","Branding"]', '["Tipografía custom","Activaciones"]', '<p>Rotulación a mano para fachadas y comercio local. Basada en Jalisco.</p><p>Color, proporción y legibilidad para fachadas y señalética.</p>', NULL, 'free', 0, NULL, NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('fernanda-ruiz-jalisco-hub3', 'Fernanda Ruiz', 'Jalisco', '["Lettering"]', '["Tipo para marca"]', '<p>Letras dibujadas a mano para identidad y campaña. Basada en Jalisco.</p><p>Boceto, refinamiento y entrega para impreso y pantalla.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('gabriel-reyes-nuevo-leon-hub0', 'Gabriel Reyes', 'Nuevo León', '["Branding"]', '["Murales","Brush","Señalética"]', '<p>Identidad tipográfica y sistemas de marca. Basada en Nuevo León.</p><p>Investigo la voz de cada marca antes de dibujar la primera letra.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('helena-garcia-nuevo-leon-hub1', 'Helena García', 'Nuevo León', '["Diseño de Tipografía","Caligrafía"]', '["Gran formato"]', '<p>Familias tipográficas a la medida y retail. Basada en Nuevo León.</p><p>Desde el concepto hasta los archivos listos para producción.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('ivan-torres-nuevo-leon-hub2', 'Iván Torres', 'Nuevo León', '["Diseño Editorial"]', '["Grabado caligráfico","Packaging"]', '<p>Diseño editorial y tipografía aplicada a publicaciones. Basada en Nuevo León.</p><p>Maquetación, elección tipográfica y ritmo de lectura.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('jimena-castillo-oaxaca-hub0', 'Jimena Castillo', 'Oaxaca', '["Caligrafía"]', '["Activaciones"]', '<p>Trazo caligráfico para invitaciones, logos y arte. Basada en Oaxaca.</p><p>Tinta, pincel y digital para encargos editoriales y de marca.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('kevin-ruiz-oaxaca-hub1', 'Kevin Ruiz', 'Oaxaca', '["Ingeniería de Fuentes","Lettering"]', '["Pizarras"]', '<p>Ingeniería tipográfica: producción, kerning y exportación. Basada en Oaxaca.</p><p>Kerning, hinting y exportación para equipos de diseño.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('lucia-reyes-oaxaca-hub2', 'Lucia Reyes', 'Oaxaca', '["Rotulación Manual"]', '["Brush","Fachada","Tipografía custom"]', '<p>Letreros y señalética con trazo manual. Basada en Oaxaca.</p><p>Letreros pintados a mano para comercio y espacios públicos.</p>', NULL, 'free', 0, NULL, '/mock/miguel-avatar.png', NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('marco-garcia-queretaro-hub0', 'Marco García', 'Querétaro', '["Lettering"]', '["Neon","Retail"]', '<p>Lettering para marca, empaques y piezas editoriales. Basada en Querétaro.</p><p>Colaboro con estudios de diseño y marcas que buscan letras con personalidad.</p>', NULL, 'pro', 0, '/mock/cover-warm.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('natalia-torres-queretaro-hub1', 'Natalia Torres', 'Querétaro', '["Branding","Diseño Editorial"]', '["Packaging"]', '<p>Branding con foco en tipografía y voz visual. Basada en Querétaro.</p><p>Sistemas tipográficos para identidad en todos los puntos de contacto.</p>', NULL, 'free', 0, '/mock/cover-cool.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('oscar-castillo-yucatan-hub0', 'Oscar Castillo', 'Yucatán', '["Diseño de Tipografía"]', '["Talleres"]', '<p>Diseño de fuentes para editorial, marca y pantalla. Basada en Yucatán.</p><p>Familias a medida y ajustes finos para editorial y UI.</p>', NULL, 'free', 0, '/mock/cover-pink.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('paula-ruiz-yucatan-hub1', 'Paula Ruiz', 'Yucatán', '["Diseño Editorial"]', '["Señalética"]', '<p>Libros, revistas y piezas impresas con cuidado tipográfico. Basada en Yucatán.</p><p>Libros, revistas y catálogos con cuidado en cada página.</p>', NULL, 'free', 0, '/mock/cover-green.svg', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('rafael-reyes-veracruz-hub0', 'Rafael Reyes', 'Veracruz', '["Caligrafía","Rotulación Manual"]', '["Fachada","Tipo para marca"]', '<p>Caligrafía contemporánea para marca y piezas únicas. Basada en Veracruz.</p><p>Piezas únicas para invitaciones, logotipos y proyectos especiales.</p>', NULL, 'free', 0, '/mock/cecilia-featured.png', NULL, NULL, '[]', 'published');
INSERT INTO profiles (slug, name, estado, servicios, tags, description, website, tier, featured, cover, avatar, custom_css, custom_fonts, status) VALUES ('sofia-garcia-veracruz-hub1', 'Sofía García', 'Veracruz', '["Ingeniería de Fuentes"]', '["Retail"]', '<p>Soporte técnico para diseñadores de fuentes. Basada en Veracruz.</p><p>Soporte técnico para lanzar fuentes sin sorpresas.</p>', NULL, 'free', 0, '/mock/mara-featured.png', NULL, NULL, '[]', 'published');

INSERT INTO profile_publications (
  slug, name, estado, servicios, tags, description, website, tier, featured,
  cover, avatar, custom_css, custom_fonts, galleries
)
SELECT
  slug, name, estado, servicios, tags, description, website, tier, featured,
  cover, avatar, custom_css, custom_fonts, galleries
FROM profiles
WHERE status = 'published';
