baseURL = "https://dimela.mx"
title = "DIMELA.mx - Directorio Mexicano de Letristas"
theme = "DIMELA-theme"

languageCode = 'es-419'
languageName = 'Spanish'

[menu]
  [[menu.main]]
    identifier = "directorio"
    name = "Directorio"
    url = "/directorio"
    weight = 10
